# Generated by Django 4.2.30 on 2026-04-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код образца')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('status', models.CharField(max_length=255, verbose_name='Статус содержания')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('summary', models.TextField(verbose_name='Сводка')),
                ('containment_protocol', models.TextField(verbose_name='Протокол содержания')),
                ('threat_level', models.CharField(max_length=64, verbose_name='Уровень угрозы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'образец',
                'verbose_name_plural': 'образцы',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название инцидента')),
                ('description', models.TextField(verbose_name='Описание инцидента')),
                ('response_protocol', models.CharField(max_length=255, verbose_name='Протокол реагирования')),
                ('severity', models.CharField(max_length=64, verbose_name='Уровень серьёзности')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Устранён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='archive.specimen', verbose_name='Образец')),
            ],
            options={
                'verbose_name': 'инцидент',
                'verbose_name_plural': 'инциденты',
                'ordering': ['-created_at'],
            },
        ),
    ]
