# Generated by Django 4.2.30 on 2026-04-22 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='response_protocol',
            field=models.CharField(choices=[('Наблюдение', 'Наблюдение'), ('Изолировать', 'Изолировать'), ('Карантин', 'Карантин')], default='Наблюдение', max_length=32, verbose_name='Протокол реагирования'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий'), ('Критический', 'Критический')], default='Средний', max_length=32, verbose_name='Уровень серьёзности'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='status',
            field=models.CharField(choices=[('Наблюдение', 'Наблюдение'), ('Контур содержания II', 'Контур содержания II'), ('Контур содержания III', 'Контур содержания III'), ('Контур содержания IV', 'Контур содержания IV'), ('Карантинный контур', 'Карантинный контур')], default='Контур содержания II', max_length=64, verbose_name='Статус содержания'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='threat_level',
            field=models.CharField(choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий'), ('Критический', 'Критический')], default='Средний', max_length=32, verbose_name='Уровень угрозы'),
        ),
        migrations.CreateModel(
            name='ResolutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_role', models.CharField(choices=[('Исследователь', 'Исследователь'), ('Оператор', 'Оператор'), ('Наблюдатель', 'Наблюдатель')], max_length=32, verbose_name='Выбранная роль')),
                ('selected_protocol', models.CharField(blank=True, choices=[('Наблюдение', 'Наблюдение'), ('Изолировать', 'Изолировать'), ('Карантин', 'Карантин')], max_length=32, verbose_name='Выбранный протокол')),
                ('recommended_protocol', models.CharField(blank=True, choices=[('Наблюдение', 'Наблюдение'), ('Изолировать', 'Изолировать'), ('Карантин', 'Карантин')], max_length=32, verbose_name='Рекомендованный протокол')),
                ('outcome', models.CharField(choices=[('success', 'Стабилизирован'), ('partial', 'Под наблюдением'), ('escalation', 'Эскалация'), ('review_only', 'Режим просмотра')], max_length=24, verbose_name='Исход')),
                ('result_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок результата')),
                ('final_status_text', models.CharField(max_length=255, verbose_name='Итоговый статус')),
                ('result_summary', models.TextField(verbose_name='Сводка результата')),
                ('system_note', models.TextField(verbose_name='Системная заметка')),
                ('was_incident_active', models.BooleanField(default=False, verbose_name='Был активный инцидент')),
                ('previous_severity', models.CharField(blank=True, choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий'), ('Критический', 'Критический')], max_length=32, verbose_name='Предыдущая серьёзность')),
                ('previous_resolved_state', models.BooleanField(default=False, verbose_name='Предыдущее состояние устранения')),
                ('new_severity', models.CharField(blank=True, choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий'), ('Критический', 'Критический')], max_length=32, verbose_name='Новая серьёзность')),
                ('new_resolved_state', models.BooleanField(default=False, verbose_name='Новое состояние устранения')),
                ('ui_theme_state', models.CharField(choices=[('success', 'Стабилизация'), ('partial', 'Контроль'), ('escalation', 'Эскалация'), ('review', 'Просмотр')], default='review', max_length=24, verbose_name='Тема интерфейса')),
                ('escalation_flag', models.BooleanField(default=False, verbose_name='Флаг эскалации')),
                ('stabilization_flag', models.BooleanField(default=False, verbose_name='Флаг стабилизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(verbose_name='Дата завершения')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_logs', to='archive.incident', verbose_name='Инцидент')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_logs', to='archive.specimen', verbose_name='Образец')),
            ],
            options={
                'verbose_name': 'сессия доступа',
                'verbose_name_plural': 'сессии доступа',
                'ordering': ['-completed_at', '-created_at'],
            },
        ),
    ]
