# Generated by Django 4.2.30 on 2026-04-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_normalize_choice_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='response_protocol',
            field=models.CharField(choices=[('Авто', 'Авто'), ('Наблюдение', 'Наблюдение'), ('Изолировать', 'Изолировать'), ('Карантин', 'Карантин')], default='Авто', max_length=32, verbose_name='Протокол реагирования'),
        ),
        migrations.AlterField(
            model_name='resolutionlog',
            name='recommended_protocol',
            field=models.CharField(blank=True, choices=[('Авто', 'Авто'), ('Наблюдение', 'Наблюдение'), ('Изолировать', 'Изолировать'), ('Карантин', 'Карантин')], max_length=32, verbose_name='Рекомендованный протокол'),
        ),
        migrations.AlterField(
            model_name='resolutionlog',
            name='selected_protocol',
            field=models.CharField(blank=True, choices=[('Авто', 'Авто'), ('Наблюдение', 'Наблюдение'), ('Изолировать', 'Изолировать'), ('Карантин', 'Карантин')], max_length=32, verbose_name='Выбранный протокол'),
        ),
    ]
